//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreSimulator/FoundationXPCProtocolProxyable-Protocol.h>
#import <CoreSimulator/SimDeviceIOPortDescriptorState-Protocol.h>

@protocol SimDisplayDescriptorState <FoundationXPCProtocolProxyable, SimDeviceIOPortDescriptorState>
@property(readonly, nonatomic) unsigned int defaultHeightForDisplay;
@property(readonly, nonatomic) unsigned int defaultWidthForDisplay;
@property(readonly, nonatomic) unsigned short displayClass;
@end

