//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreSimulator/NSObject-Protocol.h>

@class NSArray, NSObject, NSUUID;
@protocol SimDeviceIOPortConsumer, SimDeviceIOPortInterface;

@protocol SimDeviceIOProtocol <NSObject>
- (void)detachConsumer:(NSObject<SimDeviceIOPortConsumer> *)arg1 fromPort:(NSObject<SimDeviceIOPortInterface> *)arg2;
- (void)attachConsumer:(NSObject<SimDeviceIOPortConsumer> *)arg1 toPort:(NSObject<SimDeviceIOPortInterface> *)arg2;
- (NSArray<SimDeviceIOPortInterface> *)ioPorts;
- (NSObject<SimDeviceIOPortInterface> *)ioPortForUUID:(NSUUID *)arg1;
@end

