//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SimLocalThrowable : NSObject
{
    id _data;
}

+ (id)throwableWithData:(id)arg1;
@property(retain, nonatomic) id data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)initWithData:(id)arg1;

@end

