//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SimulatorKit/_TtP12SimulatorKit32SimDisplayRenderableViewDelegate_-Protocol.h>

@class _TtC12SimulatorKit24SimDisplayRenderableView;

@protocol _TtP12SimulatorKit40SimDisplayRenderableViewRotationDelegate_ <_TtP12SimulatorKit32SimDisplayRenderableViewDelegate_>
- (void)simDisplayRenderableWithView:(_TtC12SimulatorKit24SimDisplayRenderableView *)arg1 didRotateTo:(double)arg2;
@end

