//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SimulatorKit/FoundationXPCProtocolProxyable-Protocol.h>

@class NSString, NSUUID;

@protocol SimDeviceIOPortConsumer <FoundationXPCProtocolProxyable>
@property(readonly, nonatomic) NSUUID *consumerUUID;
@property(readonly, nonatomic) NSString *consumerIdentifier;
@end

