//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SimulatorKit/SimDisplayRenderableView.h>

@class NSString, NSUUID;

@interface SimDisplayRenderableView (SimulatorKit)
@property(nonatomic, readonly) NSString *consumerIdentifier;
@property(nonatomic, readonly) NSUUID *consumerUUID;
@end

