//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <SimulatorKit/SimDeviceIOPortConsumer-Protocol.h>
#import <SimulatorKit/SimDisplayDamageRectangleDelegate-Protocol.h>
#import <SimulatorKit/SimDisplayIOSurfaceRenderableDelegate-Protocol.h>
#import <SimulatorKit/SimDisplayRotationAngleDelegate-Protocol.h>

@class NSMapTable, NSString, NSUUID, SimDevice;
@protocol OS_dispatch_queue;

@interface SimDeviceFramebufferService : NSObject <SimDeviceIOPortConsumer, SimDisplayDamageRectangleDelegate, SimDisplayIOSurfaceRenderableDelegate, SimDisplayRotationAngleDelegate>
{
    BOOL _consumerAttached;
    unsigned short _displayClass;
    SimDevice *_device;
    NSString *_consumerIdentifier;
    NSUUID *_consumerUUID;
    NSObject<OS_dispatch_queue> *_executionQueue;
    NSMapTable *_clientsToCallbackQueue;
}

+ (id)tvOutFramebufferServiceForDevice:(id)arg1 error:(id *)arg2;
+ (id)mainScreenFramebufferServiceForDevice:(id)arg1 error:(id *)arg2;
+ (id)portForDisplayClass:(unsigned short)arg1 io:(id)arg2;
@property(retain, nonatomic) NSMapTable *clientsToCallbackQueue; // @synthesize clientsToCallbackQueue=_clientsToCallbackQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *executionQueue; // @synthesize executionQueue=_executionQueue;
@property(nonatomic) unsigned short displayClass; // @synthesize displayClass=_displayClass;
@property(retain, nonatomic) NSUUID *consumerUUID; // @synthesize consumerUUID=_consumerUUID;
@property(retain, nonatomic) NSString *consumerIdentifier; // @synthesize consumerIdentifier=_consumerIdentifier;
@property(nonatomic) BOOL consumerAttached; // @synthesize consumerAttached=_consumerAttached;
@property(nonatomic) __weak SimDevice *device; // @synthesize device=_device;
- (void).cxx_destruct;
- (void)didReceiveDamageRect:(struct CGRect)arg1;
- (void)didChangeIOSurface:(id)arg1;
- (void)didChangeDisplayAngle:(double)arg1;
- (void)requestDeviceDimensions:(struct CGSize)arg1 scaledDimensions:(struct CGSize)arg2;
- (void)resume;
- (void)_ON_EXECUTION_QUEUE_sendSetIOSurfaceToClients:(struct __IOSurface *)arg1;
- (void)unregisterClient:(id)arg1;
- (void)registerClient:(id)arg1 onQueue:(id)arg2;
- (void)invalidate;
- (void)dealloc;
- (id)initWithName:(id)arg1 displayClass:(unsigned short)arg2 device:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

