//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SimulatorKit/NSObject-Protocol.h>

@class NSArray, NSUUID;
@protocol SimDeviceIOPortConsumer, SimDeviceIOPortInterface;

@protocol SimDeviceIOProtocol <NSObject>
- (void)detachConsumer:(id <SimDeviceIOPortConsumer>)arg1 fromPort:(id <SimDeviceIOPortInterface>)arg2;
- (void)attachConsumer:(id <SimDeviceIOPortConsumer>)arg1 toPort:(id <SimDeviceIOPortInterface>)arg2;
- (id <SimDeviceIOPortInterface>)ioPortForUUID:(NSUUID *)arg1;
- (NSArray *)ioPorts;
@end

