//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, NSUUID;

__attribute__((visibility("hidden")))
@interface SimDisplayScreenshotWriter : NSObject
{
    // Error parsing type: , name: fileType
    // Error parsing type: , name: consumerUUID
    // Error parsing type: , name: consumerIdentifier
    // Error parsing type: , name: _io
    // Error parsing type: , name: _port
    // Error parsing type: , name: _queue
    // Error parsing type: , name: _ioSurface
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)writeScreenshotAsyncWithOutputStream:(id)arg1 completionQueue:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)writeScreenshotWithOutputStream:(id)arg1 error:(id *)arg2;
- (void)dealloc;
- (id)initWithIo:(id)arg1 displayClass:(unsigned short)arg2 error:(id *)arg3;
- (id)initWithIo:(id)arg1 port:(id)arg2 fileType:(long long)arg3 error:(id *)arg4;
@property(nonatomic, retain) struct __IOSurface *_ioSurface; // @synthesize _ioSurface;
@property(nonatomic, readonly) NSString *consumerIdentifier; // @synthesize consumerIdentifier;
@property(nonatomic, readonly) NSUUID *consumerUUID; // @synthesize consumerUUID;
@property(nonatomic, readonly) long long fileType; // @synthesize fileType;

@end

