//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <SimulatorKit/SimDeviceIOPortConsumer-Protocol.h>
#import <SimulatorKit/SimDisplayDamageRectangleDelegate-Protocol.h>
#import <SimulatorKit/SimDisplayIOSurfaceRenderableDelegate-Protocol.h>

@class MTLTextureDescriptor, NSOutputStream, NSString, NSUUID, SimVideoFile;
@protocol MTLCommandQueue, MTLComputePipelineState, MTLDevice, MTLFunction, MTLLibrary, OS_dispatch_queue;

@interface SimDisplayVideoWriter : NSObject <SimDeviceIOPortConsumer, SimDisplayDamageRectangleDelegate, SimDisplayIOSurfaceRenderableDelegate>
{
    BOOL _startedWriting;
    double _framesPerSecond;
    unsigned long long _timeScale;
    NSUUID *_consumerUUID;
    NSString *_consumerIdentifier;
    NSObject<OS_dispatch_queue> *_executionQueue;
    id <MTLDevice> _metalDevice;
    id <MTLLibrary> _metalLibrary;
    id <MTLCommandQueue> _metalCommandQueue;
    id <MTLFunction> _kernelFunction;
    id <MTLComputePipelineState> _pipelineState;
    struct __CVMetalTextureCache *_metalTextureCache;
    MTLTextureDescriptor *_ioSurfaceTextureDescriptor;
    NSOutputStream *_stream;
    SimVideoFile *_videoFile;
    id _ioSurface;
    struct OpaqueVTCompressionSession *_compressionSession;
    CDStruct_1b6d18a9 _startTime;
    CDStruct_1b6d18a9 _lastEncodeTime;
}

+ (id)videoWriterForURL:(id)arg1 fileType:(id)arg2;
+ (id)videoWriterForOutputStream:(id)arg1 fileType:(id)arg2;
+ (id)videoWriter;
@property(nonatomic) CDStruct_1b6d18a9 lastEncodeTime; // @synthesize lastEncodeTime=_lastEncodeTime;
@property(nonatomic) CDStruct_1b6d18a9 startTime; // @synthesize startTime=_startTime;
@property(nonatomic) struct OpaqueVTCompressionSession *compressionSession; // @synthesize compressionSession=_compressionSession;
@property(retain, nonatomic) id ioSurface; // @synthesize ioSurface=_ioSurface;
@property(nonatomic) BOOL startedWriting; // @synthesize startedWriting=_startedWriting;
@property(retain, nonatomic) SimVideoFile *videoFile; // @synthesize videoFile=_videoFile;
@property(retain, nonatomic) NSOutputStream *stream; // @synthesize stream=_stream;
@property(retain, nonatomic) MTLTextureDescriptor *ioSurfaceTextureDescriptor; // @synthesize ioSurfaceTextureDescriptor=_ioSurfaceTextureDescriptor;
@property(nonatomic) struct __CVMetalTextureCache *metalTextureCache; // @synthesize metalTextureCache=_metalTextureCache;
@property(retain, nonatomic) id <MTLComputePipelineState> pipelineState; // @synthesize pipelineState=_pipelineState;
@property(retain, nonatomic) id <MTLFunction> kernelFunction; // @synthesize kernelFunction=_kernelFunction;
@property(retain, nonatomic) id <MTLCommandQueue> metalCommandQueue; // @synthesize metalCommandQueue=_metalCommandQueue;
@property(retain, nonatomic) id <MTLLibrary> metalLibrary; // @synthesize metalLibrary=_metalLibrary;
@property(retain, nonatomic) id <MTLDevice> metalDevice; // @synthesize metalDevice=_metalDevice;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *executionQueue; // @synthesize executionQueue=_executionQueue;
@property(retain, nonatomic) NSString *consumerIdentifier; // @synthesize consumerIdentifier=_consumerIdentifier;
@property(retain, nonatomic) NSUUID *consumerUUID; // @synthesize consumerUUID=_consumerUUID;
@property(nonatomic) unsigned long long timeScale; // @synthesize timeScale=_timeScale;
@property(nonatomic) double framesPerSecond; // @synthesize framesPerSecond=_framesPerSecond;
- (void).cxx_destruct;
- (void)startWriting;
- (void)finishWriting;
- (void)didReceiveDamageRect:(struct CGRect)arg1;
- (void)didChangeIOSurface:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

