//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SimulatorKit/SimVideoFile.h>

@class NSMutableArray, NSMutableData, SimVideoQuicktimeFormat;

@interface SimVideoMP4File : SimVideoFile
{
    BOOL _wroteHeader;
    SimVideoQuicktimeFormat *_qtFormat;
    unsigned long long _bytesWritten;
    NSMutableData *_mediaData;
    NSMutableArray *_mediaSizes;
    NSMutableArray *_mediaDecodeTimes;
    NSMutableArray *_mediaDurationTimes;
    NSMutableArray *_mediaPresentationTimes;
}

+ (void)parameterSetsForFormatDescription:(const struct opaqueCMFormatDescription *)arg1 sequenceParameterSetData:(id *)arg2 pictureParameterSetData:(id *)arg3;
+ (BOOL)isSampleBufferIFrame:(struct opaqueCMSampleBuffer *)arg1;
@property(retain, nonatomic) NSMutableArray *mediaPresentationTimes; // @synthesize mediaPresentationTimes=_mediaPresentationTimes;
@property(retain, nonatomic) NSMutableArray *mediaDurationTimes; // @synthesize mediaDurationTimes=_mediaDurationTimes;
@property(retain, nonatomic) NSMutableArray *mediaDecodeTimes; // @synthesize mediaDecodeTimes=_mediaDecodeTimes;
@property(retain, nonatomic) NSMutableArray *mediaSizes; // @synthesize mediaSizes=_mediaSizes;
@property(retain, nonatomic) NSMutableData *mediaData; // @synthesize mediaData=_mediaData;
@property(nonatomic) unsigned long long bytesWritten; // @synthesize bytesWritten=_bytesWritten;
@property(nonatomic) BOOL wroteHeader; // @synthesize wroteHeader=_wroteHeader;
@property(retain, nonatomic) SimVideoQuicktimeFormat *qtFormat; // @synthesize qtFormat=_qtFormat;
- (void).cxx_destruct;
- (void)writeSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 completionQueue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)writeMovieWithMedia:(BOOL)arg1;
- (void)setTimeScale:(double)arg1;
- (void)closeFile;
- (id)initVideoFileForOutputStream:(id)arg1 error:(id *)arg2;

@end

