//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSDate;

@interface SimVideoQuicktimeFormat : NSObject
{
    unsigned char _qtFormatType;
    BOOL _fragmented;
    NSDate *_creationDate;
    NSDate *_modificationDate;
    NSArray *_sequenceParameterSets;
    NSArray *_pictureParameterSets;
    double _timeScale;
    struct CGSize _frameSize;
}

+ (double)timeIntervalSinceQuicktimeEpochWithDate:(id)arg1;
+ (id)formatWithType:(unsigned char)arg1;
@property(nonatomic) BOOL fragmented; // @synthesize fragmented=_fragmented;
@property(nonatomic) double timeScale; // @synthesize timeScale=_timeScale;
@property(retain, nonatomic) NSArray *pictureParameterSets; // @synthesize pictureParameterSets=_pictureParameterSets;
@property(retain, nonatomic) NSArray *sequenceParameterSets; // @synthesize sequenceParameterSets=_sequenceParameterSets;
@property(nonatomic) struct CGSize frameSize; // @synthesize frameSize=_frameSize;
@property(retain, nonatomic) NSDate *modificationDate; // @synthesize modificationDate=_modificationDate;
@property(retain, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(nonatomic) unsigned char qtFormatType; // @synthesize qtFormatType=_qtFormatType;
- (void).cxx_destruct;
- (id)dictionaryForMovieFragment;
- (id)dictionaryForMovie;
- (id)dataForHeader;

@end

